set_property SRC_FILE_INFO {cfile:/home/cho/test/test/shell-ku3-xillybus-ap_fifo128/vivado-essentials/xillydemo.xdc rfile:../../../vivado-essentials/xillydemo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks txoutclk_out*] -to [get_clocks clk_out?_clk_wiz_0*]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out?_clk_wiz_0*] -to [get_clocks txoutclk_out*]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async1 -asynchronous -group [get_clocks -include_generated_clocks -of_objects [get_ports PCIE_REFCLK_P]] -group [get_clocks -include_generated_clocks -of_objects [get_pins [all_fanin -flat -startpoints_only [get_pins -hier -filter {name=~*/gt_top_i/phy_clk_i/CLK_USERCLK_IN}]]]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC [get_package_pins -filter {PIN_FUNC == IO_T3U_N12_PERSTN0_65}] [get_ports PCIE_PERST_B_LS]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB6 [get_cells -hier -filter {name=~*/pcieclk_ibuf} ]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict "PACKAGE_PIN AP8 IOSTANDARD LVCMOS18" [get_ports "GPIO_LED[0]"]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict "PACKAGE_PIN H23 IOSTANDARD LVCMOS18" [get_ports "GPIO_LED[1]"]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict "PACKAGE_PIN P20 IOSTANDARD LVCMOS18" [get_ports "GPIO_LED[2]"]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict "PACKAGE_PIN P21 IOSTANDARD LVCMOS18" [get_ports "GPIO_LED[3]"]
